Repository TeamS2-ICCAS2024/ZEN-server, pull requests merged in 2024-07, with the labels that each got.

#2 [feat] 응답 관련 기초셋팅
  .github/pull_request_template.md
  ZenServer/build.gradle
  ZenServer/src/main/java/com/zen/ZenServer/api/TestController.java
  ZenServer/src/main/java/com/zen/ZenServer/global/exception/BadRequestException.java
  ZenServer/src/main/java/com/zen/ZenServer/global/exception/CustomException.java
  ZenServer/src/main/java/com/zen/ZenServer/global/exception/GlobalExceptionHandler.java
  ZenServer/src/main/java/com/zen/ZenServer/global/exception/ResponseStatusSetterAdvice.java
  ZenServer/src/main/java/com/zen/ZenServer/global/response/ApiResponseDto.java
  ZenServer/src/main/java/com/zen/ZenServer/global/response/enums/ErrorCode.java
  ZenServer/src/main/java/com/zen/ZenServer/global/response/enums/SuccessCode.java
  ZenServer/src/main/resources/application.properties
Labels: feat, 보람

#4 Feat/#3
  .idea/.gitignore
  ZenServer/src/main/java/com/zen/ZenServer/api/user/controller/UserController.java
  ZenServer/src/main/java/com/zen/ZenServer/api/user/domain/User.java
  ZenServer/src/main/java/com/zen/ZenServer/api/user/dto/UserDto.java
  ZenServer/src/main/java/com/zen/ZenServer/api/user/repository/UserRepository.java
  ZenServer/src/main/java/com/zen/ZenServer/api/user/service/UserService.java
Labels: feat, 현욱

#11 [feat] 기획에 따른 baseHeart 도메인 기능 구현
  ZenServer/src/main/java/com/zen/ZenServer/api/baseHeart/controller/BaseHeartController.java
  ZenServer/src/main/java/com/zen/ZenServer/api/baseHeart/domain/BaseHeart.java
  ZenServer/src/main/java/com/zen/ZenServer/api/baseHeart/dto/request/BaseHeartSaveRequest.java
  ZenServer/src/main/java/com/zen/ZenServer/api/baseHeart/dto/response/BaseHeartResponse.java
  ZenServer/src/main/java/com/zen/ZenServer/api/baseHeart/repository/BaseHeartRepository.java
  ZenServer/src/main/java/com/zen/ZenServer/api/baseHeart/service/BaseHeartService.java
  ZenServer/src/main/java/com/zen/ZenServer/global/auth/domain/Token.java
  ZenServer/src/main/java/com/zen/ZenServer/global/auth/service/AuthenticationService.java
  ZenServer/src/main/java/com/zen/ZenServer/global/jwt/JwtTokenProvider.java
  ZenServer/src/main/java/com/zen/ZenServer/global/response/enums/ErrorCode.java
  ZenServer/src/main/java/com/zen/ZenServer/global/response/enums/SuccessCode.java
Labels: feat, 지원

#14 [feat] user 답변 저장 api 구현
  ZenServer/build.gradle
  ZenServer/src/main/java/com/zen/ZenServer/ZenServerApplication.java
  ZenServer/src/main/java/com/zen/ZenServer/api/emotionDiary/controller/EmotionDiaryController.java
  ZenServer/src/main/java/com/zen/ZenServer/api/emotionDiary/domain/EmotionDiary.java
  ZenServer/src/main/java/com/zen/ZenServer/api/emotionDiary/domain/UserCharacter.java
  ZenServer/src/main/java/com/zen/ZenServer/api/emotionDiary/dto/EmotionDiaryPostRequest.java
  ZenServer/src/main/java/com/zen/ZenServer/api/emotionDiary/repository/EmotionDiaryRepository.java
  ZenServer/src/main/java/com/zen/ZenServer/api/emotionDiary/service/EmotionDiaryService.java
  ZenServer/src/main/java/com/zen/ZenServer/api/user/controller/UserController.java
  ZenServer/src/main/java/com/zen/ZenServer/api/user/domain/User.java
  ZenServer/src/main/java/com/zen/ZenServer/global/client/gpt/GptProperties.java
  ZenServer/src/main/java/com/zen/ZenServer/global/client/gpt/GptRequest.java
  ZenServer/src/main/java/com/zen/ZenServer/global/client/gpt/GptResponse.java
  ZenServer/src/main/java/com/zen/ZenServer/global/client/gpt/GptService.java
  ZenServer/src/main/java/com/zen/ZenServer/global/client/gpt/Message.java
  ZenServer/src/main/java/com/zen/ZenServer/global/config/GptConfig.java
  ZenServer/src/main/java/com/zen/ZenServer/global/config/WebClientConfig.java
  ZenServer/src/main/java/com/zen/ZenServer/global/domain/BaseTimeEntity.java
  ZenServer/src/main/java/com/zen/ZenServer/global/response/enums/ErrorCode.java
  ZenServer/src/main/java/com/zen/ZenServer/global/response/enums/SuccessCode.java
Labels: feat, 보람

#16 [feat] gpt 응답형태 고도화
  ZenServer/src/main/java/com/zen/ZenServer/api/emotionDiary/controller/EmotionDiaryController.java
  ZenServer/src/main/java/com/zen/ZenServer/global/client/gpt/GptService.java
  ZenServer/src/main/java/com/zen/ZenServer/global/jwt/JwtAuthenticationFilter.java
  ZenServer/src/main/java/com/zen/ZenServer/global/security/SecurityConfig.java
Labels: feat, 보람

#22 [feat] 유저에 해당하는 일기 전체 조회 api 구현
  ZenServer/src/main/java/com/zen/ZenServer/api/emotionDiary/controller/EmotionDiaryController.java
  ZenServer/src/main/java/com/zen/ZenServer/api/emotionDiary/dto/request/EmotionDiaryPostRequest.java
  ZenServer/src/main/java/com/zen/ZenServer/api/emotionDiary/dto/response/EmotionDiaryListGetResponse.java
  ZenServer/src/main/java/com/zen/ZenServer/api/emotionDiary/repository/EmotionDiaryRepository.java
  ZenServer/src/main/java/com/zen/ZenServer/api/emotionDiary/service/EmotionDiaryService.java
  ZenServer/src/main/java/com/zen/ZenServer/api/user/repository/UserRepository.java
  ZenServer/src/main/java/com/zen/ZenServer/global/Util/DateUtil.java
  ZenServer/src/main/java/com/zen/ZenServer/global/client/gpt/GptService.java
  ZenServer/src/main/java/com/zen/ZenServer/global/response/enums/SuccessCode.java
Labels: feat, 보람

#26 [feat] 감정에 해당하는 일기 조회 api 구현
  ZenServer/src/main/java/com/zen/ZenServer/api/emotionDiary/controller/EmotionDiaryController.java
  ZenServer/src/main/java/com/zen/ZenServer/api/emotionDiary/dto/request/DiaryPostRequest.java
  ZenServer/src/main/java/com/zen/ZenServer/api/emotionDiary/dto/response/DiaryDetailGetResponse.java
  ZenServer/src/main/java/com/zen/ZenServer/api/emotionDiary/dto/response/DiaryListGetResponse.java
  ZenServer/src/main/java/com/zen/ZenServer/api/emotionDiary/repository/EmotionDiaryRepository.java
  ZenServer/src/main/java/com/zen/ZenServer/api/emotionDiary/service/EmotionDiaryService.java
  ZenServer/src/main/java/com/zen/ZenServer/global/client/gpt/GptService.java
  ZenServer/src/main/java/com/zen/ZenServer/global/response/enums/SuccessCode.java
Labels: feat, 보람
